Assessment-3
sjdonado/assessment-3-backend-un-202130 pull request #12
Opened 2021-10-25 18:40 UTC by kangcheng322

Nombre: Kang 
Código: 200108179

2021-10-26 17:22 UTC, sjdonado commented on package.json
> +    "eslint-plugin-import": "^2.25.2",
en el enunciado de la evaluación se especifica no modificar este archivo

2021-10-26 19:02 UTC, sjdonado requested changes
cambiar version eslint-plugin-import

2021-10-26 20:17 UTC, kangcheng322 commented on package.json
> +    "eslint-plugin-import": "^2.25.2",
Buenas tardes, ya hice los cambios para que lo pueda revisar.

2021-10-27 06:31 UTC, sjdonado approved these changes
Buen trabajo

2021-10-27 06:31 UTC, closed without merging